/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface LibCommitmentTestInterface extends utils.Interface {
  functions: {
    "eq(uint256,uint256)": FunctionFragment;
    "fromSecret(uint256)": FunctionFragment;
    "zero()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "eq",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fromSecret",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "zero", values?: undefined): string;

  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fromSecret", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zero", data: BytesLike): Result;

  events: {};
}

export interface LibCommitmentTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibCommitmentTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eq(
      a_: BigNumberish,
      b_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { eq_: boolean }>;

    fromSecret(
      secret_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { commitment_: BigNumber }>;

    zero(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { zero_: BigNumber }>;
  };

  eq(
    a_: BigNumberish,
    b_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  fromSecret(
    secret_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  zero(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    eq(
      a_: BigNumberish,
      b_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    fromSecret(
      secret_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zero(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    eq(
      a_: BigNumberish,
      b_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fromSecret(
      secret_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zero(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    eq(
      a_: BigNumberish,
      b_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fromSecret(
      secret_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zero(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
