/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type StorageOpcodesRangeStruct = {
  pointer: BigNumberish;
  length: BigNumberish;
};

export type StorageOpcodesRangeStructOutput = [BigNumber, BigNumber] & {
  pointer: BigNumber;
  length: BigNumber;
};

export interface RainterpreterInterface extends utils.Interface {
  functions: {
    "eval(address,uint256,uint256[][])": FunctionFragment;
    "functionPointers()": FunctionFragment;
    "storageOpcodesRange()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "eval",
    values: [string, BigNumberish, BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "functionPointers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storageOpcodesRange",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "eval", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "functionPointers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageOpcodesRange",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Rainterpreter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RainterpreterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eval(
      statePointer_: string,
      entrypoint_: BigNumberish,
      context_: BigNumberish[][],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    functionPointers(overrides?: CallOverrides): Promise<[string]>;

    storageOpcodesRange(
      overrides?: CallOverrides
    ): Promise<[StorageOpcodesRangeStructOutput]>;
  };

  eval(
    statePointer_: string,
    entrypoint_: BigNumberish,
    context_: BigNumberish[][],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  functionPointers(overrides?: CallOverrides): Promise<string>;

  storageOpcodesRange(
    overrides?: CallOverrides
  ): Promise<StorageOpcodesRangeStructOutput>;

  callStatic: {
    eval(
      statePointer_: string,
      entrypoint_: BigNumberish,
      context_: BigNumberish[][],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    functionPointers(overrides?: CallOverrides): Promise<string>;

    storageOpcodesRange(
      overrides?: CallOverrides
    ): Promise<StorageOpcodesRangeStructOutput>;
  };

  filters: {};

  estimateGas: {
    eval(
      statePointer_: string,
      entrypoint_: BigNumberish,
      context_: BigNumberish[][],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    functionPointers(overrides?: CallOverrides): Promise<BigNumber>;

    storageOpcodesRange(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    eval(
      statePointer_: string,
      entrypoint_: BigNumberish,
      context_: BigNumberish[][],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    functionPointers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storageOpcodesRange(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
