/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRainInterpreterIntegrity,
  IRainInterpreterIntegrityInterface,
} from "../IRainInterpreterIntegrity";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "pointer",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "length",
            type: "uint256",
          },
        ],
        internalType: "struct StorageOpcodesRange",
        name: "storageOpcodesRange",
        type: "tuple",
      },
      {
        internalType: "bytes[]",
        name: "sources",
        type: "bytes[]",
      },
      {
        internalType: "uint256",
        name: "constantsLength",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "finalStacks",
        type: "uint256[]",
      },
    ],
    name: "ensureIntegrity",
    outputs: [
      {
        internalType: "uint256",
        name: "scratch",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "contextScratch_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximumStackHeight",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRainInterpreterIntegrity__factory {
  static readonly abi = _abi;
  static createInterface(): IRainInterpreterIntegrityInterface {
    return new utils.Interface(_abi) as IRainInterpreterIntegrityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRainInterpreterIntegrity {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRainInterpreterIntegrity;
  }
}
