/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SeedERC20ForceSendEther,
  SeedERC20ForceSendEtherInterface,
} from "../SeedERC20ForceSendEther";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "contract SeedERC20",
        name: "seedERC20Contract_",
        type: "address",
      },
    ],
    name: "destroy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060c68061001f6000396000f3fe608060405260043610601c5760003560e01c8062f55d9d14602457005b36602257005b005b348015602f57600080fd5b506022603b3660046055565b8073ffffffffffffffffffffffffffffffffffffffff8116ff5b600060208284031215606657600080fd5b813573ffffffffffffffffffffffffffffffffffffffff81168114608957600080fd5b939250505056fea2646970667358221220f7b27a7676f7868b0d18fbb0dba94b071340f1f7f2f34f27dcbfbe623681c12a64736f6c634300080a0033";

type SeedERC20ForceSendEtherConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SeedERC20ForceSendEtherConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SeedERC20ForceSendEther__factory extends ContractFactory {
  constructor(...args: SeedERC20ForceSendEtherConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SeedERC20ForceSendEther> {
    return super.deploy(overrides || {}) as Promise<SeedERC20ForceSendEther>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SeedERC20ForceSendEther {
    return super.attach(address) as SeedERC20ForceSendEther;
  }
  connect(signer: Signer): SeedERC20ForceSendEther__factory {
    return super.connect(signer) as SeedERC20ForceSendEther__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SeedERC20ForceSendEtherInterface {
    return new utils.Interface(_abi) as SeedERC20ForceSendEtherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SeedERC20ForceSendEther {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SeedERC20ForceSendEther;
  }
}
